stages:
  - build
  - release

build_job:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Building project"
    - cp ARM64/install.tar.gz Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl
    - cp x64/install.tar.gz Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl
  artifacts:
    paths:
      - Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl
      - Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl
    expire_in: 1 week

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running the WSL release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'WSL Release $CI_COMMIT_TAG'
    description: |
        Release for people who want to use Debian in WSL2 without using the Windows Store.
        More information: https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro
    assets:
      links:
        - name: 'Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl'
          url: '${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl'
        - name: 'Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl'
          url: '${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl'