name: Build and Release Debian WSL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,16 * ?'

permissions:
  contents: write

jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: run script
        id: run-script
        run: |
          echo "Building rootfs"
          sh ./create-targz.sh
