name: Build and Release Debian WSL

on:
  schedule:
    - cron: '0 0 1,16 * ?'

jobs:
  build_job:
    name: build
    runs-on: debian-latest
    steps:
      - name: run script
        id: run-script
        run: |
          echo "Building project"
          cp ARM64/install.tar.gz Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl
          cp x64/install.tar.gz Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl
          echo "BUILD_JOB_ID=$CI_JOB_ID" > build_job.env
  artifacts:
    paths:
      - Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl
      - Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl
      - build_job.env
    expire_in: 1 week

  release_job:
    name: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    setps:
      run: |
        echo "Running the WSL release job."
      needs: build_job
      artifacts:
         reports:
         dotenv: build_job.env
      release:
         tag_name: $CI_COMMIT_TAG
         name: 'WSL Release $CI_COMMIT_TAG'
          description: |
        Release for people who want to use Debian in WSL2 without using the Windows Store.
        More information: https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro
        assets:
         links:
          - name: 'Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl'
             url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/Debian_WSL_ARM64_$CI_COMMIT_TAG.wsl'
             link_type: 'package'
          - name: 'Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl'
            url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/Debian_WSL_AMD64_$CI_COMMIT_TAG.wsl'
            link_type: 'package'
