name: Build and Release Debian WSL

on:
  schedule:
    - cron: '0 0 1,16 * ?'

jobs:
  build_job:
    name: build
    runs-on: debian-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: run script
        id: run-script
        run: |
          echo "Building rootfs"
          sh ./create-targz.sh
